### ISSUE TITLE
Allow configuration of which attributes to check for valid Tailwind classes

### ISSUE THREAD

**Issue by uncenter** [hyoban/tailwindcss-classname-highlight#8]
### Clear and concise description of the problem

I don't need to see that `contents` in `aria-label="Table of contents"` is a valid TailwindCSS class.

### Suggested solution

Ideally this would only check for class names inside of `class` or `className` attributes. Alternatively, there could be a configuration option to set which attributes to check.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/hyoban/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/hyoban/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by hyoban** [comment]
This can sometimes be annoying, but this is [how Tailwind works](https://tailwindcss.com/docs/content-configuration#class-detection-in-depth). We have also applied [the same filtering strategy](https://github.com/unocss/unocss/issues/3278) as UnoCSS, perhaps exposing it as a setting.

https://github.com/hyoban/tailwindcss-classname-highlight/blob/dda70b8ca3199d1d311cb6baac1d645f1d51c039/src/utils.ts#L1-L6

We will not only check for class names inside of class or className attributes because we often write class names outside. Here is an example from the Tailwind doc.

```tsx
const sizes = {
  md: 'px-4 py-2 rounded-md text-base',
  lg: 'px-5 py-3 rounded-lg text-lg',
}

const colors = {
  indigo: 'bg-indigo-500 hover:bg-indigo-600 text-white',
  cyan: 'bg-cyan-600 hover:bg-cyan-700 text-white',
}

export default function Button({ color, size, children }) {
  let colorClasses = colors[color]
  let sizeClasses = sizes[size]

  return (
    <button type="button" className={`font-bold ${sizeClasses} ${colorClasses}`}>
      {children}
    </button>
  )
}
```

**Comment by uncenter** [comment]
Ah okay, fair. Thank you for the explanation!
